name: EEW-Plugin
version: 1.1.0
main: tk\hadadayo\EEW\EEW
api: [3.0.0]
commands:
 eew:
  description: "EEW command"
  usage: "/eew <on|off|status|reloadconfig|reloadlang|synctime>"
  permission: eew.eew
permissions:
 party:
  default: op
  children:
   eew.command:
    default: op