#プラグインの有効/無効
EEW: true
#受信間隔 20tick=1秒
tick: 20
origin_time_format: "Y年m月d日 H時i分s秒"

######################
#緊急地震速報 (警報)
#震度5弱以上が予想される場合
#console: コンソールにログを表示するかどうか
#broadcast: ブロードキャストメッセージを表示するかどうか
#message: プレイヤーにメッセージを表示するかどうか
#title: タイトルを表示するかどうか
#alarm: アラーム音を鳴すかどうか
#モード
#0: 受信したすべての報を通知
#1: 震央地名や予想震度が更新されたときに通知
#2: 予想震度が更新されたときに通知
#3: 最初の受信と予報/警報が切り替わったときに通知
#4: 無効
#mode
#  0: 受信したすべての報を通知
#  1: 震央地名や予想震度が更新されたときに通知
#  2: 予想震度が更新されたときに通知
#  3: 最初の受信と予報/警報が切り替わったときに通知
#  4: 無効
#
#final
#  true モードにかかわらず最終報を通知
#  false モードにかかわらず最終報を通知を無効
######################
alert:
 console:
  mode: 0
  final: true
 broadcast:
  mode: 4
  final: false
 message:
  mode: 1
  final: true
 title:
  mode: 3
  final: false
 alarm:
  mode: 3
  final: false
######################
#緊急地震速報 (予報)
#100gal以上の観測、もしくはマグニチュード3.5以上か震度3以上が予想される場合
#console: コンソールにログを表示するかどうか
#broadcast: ブロードキャストメッセージを表示するかどうか
#message: プレイヤーにメッセージを表示するかどうか
#title: タイトルを表示するかどうか
#
#mode
#  0: 受信したすべての報を通知
#  1: 震央地名や予想震度が更新されたときに通知
#  2: 予想震度が更新されたときに通知
#  3: 最初の受信と予報/警報が切り替わったときに通知
#  4: 無効
#
#final
#  true モードにかかわらず最終報を通知
#  false モードにかかわらず最終報を通知を無効
######################
forecast:
 console:
  mode: 0
  final: true
 broadcast:
  mode: 4
  final: false
 message:
  mode: 3
  final: true
 title:
  mode: 4
  final: false